version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: micorservice_db
    container_name: micorservice_db

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

  user-service:
    build:
      context: ./user-service
    depends_on:
      - postgres
      - kafka
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/micorservice_db
      KAFKA_BROKER: kafka:9093
      KAFKA_TOPIC: topic-test
    networks:
      - mynetwork

  patient-service:
    build:
      context: ./patient-service
    depends_on:
      - postgres
      - kafka
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/micorservice_db
      KAFKA_BROKER: kafka:9093
      KAFKA_TOPIC: topic-test
    networks:
      - mynetwork

volumes:
  postgres_data:


networks:
  mynetwork:
    driver: bridge
